services:
  opencent:
    build: .
    container_name: opencent
    ports:
      - "8000:8000"
    environment:
      DJANGO_SECRET_KEY: ${SECRET_KEY}
    env_file:
      - .env
    volumes:
      - .:/app
