services:
  opencent-db:
   image: postgres:18
   environment:
     POSTGRES_DB: ${DATABASE_NAME}
     POSTGRES_USER: ${DATABASE_USERNAME}
     POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
   ports:
     - "5432:5432"
   volumes:
     - opencent_db:/var/lib/postgresql
  opencent:
    image: ghcr.io/jjk4/opencent:dev
    ports:
      - "8000:8000"
    environment:
      DJANGO_SECRET_KEY: ${SECRET_KEY}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_ENGINE: ${DATABASE_ENGINE}
      DATABASE_HOST: opencent-db
      DATABASE_PORT: 5432
    depends_on:
      - opencent-db
    volumes:
      - opencent_media:/app/media

volumes:
  opencent_db:
  opencent_media: